### ISSUE TITLE
Built-in fonts

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/stylia#1]
Problem occurs during import of Stylia

The is_font_available() function in the base init.py loops through all the fonts on the system. Matplotlib in line 15 then crashes the run because it can't process some fonts (this is specifically a problem with Google's Noto emoji fonts that were natively installed in both my linux distributions).

**Comment by miquelduranfrigola** [comment]
OK probably we could put a try-except here. Could you assist me wit this?

I plan to do a major update to this library during the next few days, but won't touch the __init__.py file

**Comment by JHlozek** [comment]
Closed - see #2
