### ISSUE TITLE
Default font - Arial

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/stylia#2]
Arial was not natively installed in both my Ubuntu and CentOS systems and had to be manually added to avoid crashes. 
This could be tricky for new users who aren't used to Linux.

I suggest either a different base font or otherwise including the Arial.ttf as part of installation.

**Comment by miquelduranfrigola** [comment]
Hi @JHlozek this makes a lot of sense. We need Arial because the idea here will be to have publication-like plots (library is still under construction). I vote for having the Arial.tff font as part of the installation.

Do you think you could assist me with this?

**Comment by JHlozek** [comment]
Hi @miquelduranfrigola 
I did some digging and it seems like matplotlib has a font backend that comes pre-built with most fonts (including Arial in the 'sans-serif' family). 
So checking all local fonts and their compatibility with matplotlib in __init__.py seems to be inviting problems such as the Google Noto fonts in Issue #1.

I suggest removing that initial font check as I believe the matplotlib font_manager takes care of it and this closes both Stylia issue #1 and #2.

Could you grant me contributor access here please. I have another minor bug fix to contribute in any case.

**Comment by miquelduranfrigola** [comment]
Good insights @JHlozek, many thanks. You now have permissions, feel free to commit your changes and then close issues #1 and #2 correspondingly
