### ISSUE TITLE
Update install to pyproject.toml

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/stylia#3]
This repository is installed with the old pypi standard using a `setup.py`
We would like to move to a `pyproject.toml`

**Comment by P-Mefut** [comment]
hi @GemmaTuron , I'll love to work on this issue if you could assign it to me

**Comment by DhanshreeA** [comment]
Hi @P-Mefut go ahead. I am assigning this to you.

**Comment by P-Mefut** [comment]
Hi @DhanshreeA @GemmaTuron,

I hope you’re both doing well! I’ve created the `pyproject.toml` file and left it in backward-compatible mode for now, as `setup.py` is still supported. However, I’m considering whether to completely remove `setup.py` and rely solely on `pyproject.toml` for installations. Do you think it would be better to transition entirely to `pyproject.toml`, or should I retain `setup.py` for compatibility?

I appreciate your guidance on this!

Thank you!

**Comment by DhanshreeA** [comment]
Hi @P-Mefut always in favor of removing `setup.py` file, it is going to be fully deprecated soon so even if pip will stop complaining because it will find `pyproject.toml`, having dead code lying around is no fun.

**Comment by P-Mefut** [comment]
Okay thanks!
